language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - hhvm

before_install:
  - sudo apt-get install --yes openjdk-7-jdk
  - java -version
  - curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
  - sudo apt-get install --yes nodejs
  - npm install -g grunt-cli

install:
  - npm install
  - composer install

script:
  - ls /home/travis/build/gomoob/php-metadata-extractor/src/main/resources/jars
  - java -classpath '/home/travis/build/gomoob/php-metadata-extractor/src/main/resources/jars/metadata-extractor-2.9.1.jar' com.drew.imaging.ImageMetadataReader '/home/travis/build/gomoob/php-metadata-extractor/src/test/resources/elephant.jpg'
  - java -classpath /home/travis/build/gomoob/php-metadata-extractor/src/main/resources/jars/metadata-extractor-2.9.1.jar com.drew.imaging.ImageMetadataReader '/home/travis/build/gomoob/php-metadata-extractor/src/test/resources/elephant.jpg'
  - grunt

after_script:
  - php vendor/bin/coveralls -v
  - chmod +x code-climate-test-reporter
  - CODECLIMATE_REPO_TOKEN=iuxZEsKGmIXjOGObP1WiZ1VmOFybvyUs5 ./code-climate-test-reporter
